name: javascript-playwright-esm-pnpm

env:
  ALLURE_ENDPOINT: https://demo.testops.cloud/
  ALLURE_PROJECT_ID: 4195
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "./out/allure-results"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
        required: false
        default: ""
      ALLURE_USERNAME:
        description: "ALLURE_USERNAME - service parameter (leave blank)"
        required: false
        default: ""

permissions: write-all

jobs:
  autotests:
    name: Run tests and generate Allure Report 
    runs-on: ubuntu-latest
    
    steps:
    
    - name: "Setup pnpm"
      uses: pnpm/action-setup@v2
      with:
        version: 8
    
    - name: Clone repository
      uses: actions/checkout@v4.2.2

    - name: Set up Node 20
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 20
        cache: pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Install allure-playwright
      run: pnpm add allure-playwright --save-dev

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Install allurectl
      uses: allure-framework/setup-allurectl@v1
      with:
        allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
        allure-token: ${{ env.ALLURE_TOKEN }}
        allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

    - name: Remove old directories
      run: |
        rm -rf allure-results .allure

    - name: Run tests with Allure TestOps
      run: allurectl watch -- pnpm test
      continue-on-error: true
